"""
deadline_alert.py — Check DEADLINES.md for overdue items not logged in HEARTBEAT.md.
If any found, send email to getengram@outlook.com via smtplib (Outlook SMTP).

Usage:
    python deadline_alert.py [--dry-run]

Exit codes:
    0 — no overdue items, or all overdue items already mentioned in HEARTBEAT log
    1 — overdue items found and alert sent (or would be sent in dry-run)
    2 — error
"""
import argparse
import re
import smtplib
import sys
from datetime import date, datetime
from email.mime.text import MIMEText
from pathlib import Path

BASE = Path(r"E:\2026\ClaudesCorner")
DEADLINES_FILE = BASE / "DEADLINES.md"
HEARTBEAT_FILE = BASE / "core" / "HEARTBEAT.md"
LOG_FILE = BASE / "logs" / "deadline_alert.log"

FROM_ADDR = "getengram@outlook.com"
TO_ADDR = "getengram@outlook.com"
SMTP_HOST = "smtp-mail.outlook.com"
SMTP_PORT = 587

ENTRY_RE = re.compile(r"^-\s+(\d{4}-\d{2}-\d{2})\s+(.+)$")


def _log(msg: str) -> None:
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    line = f"[{ts}] {msg}"
    print(line, file=sys.stderr)
    LOG_FILE.parent.mkdir(exist_ok=True)
    with LOG_FILE.open("a", encoding="utf-8") as f:
        f.write(line + "\n")


def load_deadlines() -> list[dict]:
    if not DEADLINES_FILE.exists():
        return []
    today = date.today()
    items = []
    for line in DEADLINES_FILE.read_text(encoding="utf-8").splitlines():
        m = ENTRY_RE.match(line.strip())
        if m:
            d = date.fromisoformat(m.group(1))
            days = (d - today).days
            if days < 0:
                items.append({"date": str(d), "label": m.group(2).strip(), "days_overdue": abs(days)})
    return sorted(items, key=lambda x: x["date"])


def load_heartbeat_log() -> str:
    if not HEARTBEAT_FILE.exists():
        return ""
    return HEARTBEAT_FILE.read_text(encoding="utf-8").lower()


def filter_unlogged(overdue: list[dict], heartbeat: str) -> list[dict]:
    """Keep only items whose label doesn't appear in recent HEARTBEAT log entries."""
    unlogged = []
    for item in overdue:
        # Check if the deadline label appears anywhere in HEARTBEAT
        if item["label"].lower() not in heartbeat:
            unlogged.append(item)
    return unlogged


def send_email(items: list[dict], dry_run: bool) -> None:
    lines = ["The following deadlines are overdue and have no HEARTBEAT log entry:\n"]
    for item in items:
        lines.append(f"  • {item['date']} — {item['label']} (overdue by {item['days_overdue']}d)")
    lines += [
        "",
        "Add a log entry to HEARTBEAT.md or update DEADLINES.md if resolved.",
        f"\nGenerated by deadline_alert.py at {datetime.now().strftime('%Y-%m-%d %H:%M')}",
    ]
    body = "\n".join(lines)
    subject = f"[ClaudesCorner] {len(items)} overdue deadline(s)"

    if dry_run:
        print(f"DRY RUN — would send:\nSubject: {subject}\n\n{body}")
        return

    # Read password from file if available, else skip SMTP
    pw_file = BASE / "lumen_token.txt"  # reuse existing secrets file pattern
    smtp_pw_file = BASE / "secrets" / "outlook_pw.txt"
    if not smtp_pw_file.exists():
        _log("No SMTP password found at secrets/outlook_pw.txt — skipping email send")
        _log(f"Would have sent: {subject}")
        for item in items:
            _log(f"  OVERDUE: {item['date']} {item['label']} ({item['days_overdue']}d)")
        return

    password = smtp_pw_file.read_text(encoding="utf-8").strip()
    msg = MIMEText(body)
    msg["Subject"] = subject
    msg["From"] = FROM_ADDR
    msg["To"] = TO_ADDR

    try:
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(FROM_ADDR, password)
            server.sendmail(FROM_ADDR, [TO_ADDR], msg.as_string())
        _log(f"Alert sent: {subject}")
    except Exception as e:
        _log(f"SMTP error: {e}")
        sys.exit(2)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    overdue = load_deadlines()
    if not overdue:
        _log("No overdue deadlines.")
        sys.exit(0)

    heartbeat = load_heartbeat_log()
    unlogged = filter_unlogged(overdue, heartbeat)

    if not unlogged:
        _log(f"{len(overdue)} overdue deadline(s) but all referenced in HEARTBEAT — no alert needed.")
        sys.exit(0)

    _log(f"{len(unlogged)} unlogged overdue deadline(s) — sending alert.")
    send_email(unlogged, args.dry_run)
    sys.exit(1)


if __name__ == "__main__":
    main()
